# Generated by Django 2.0 on 2017-12-29 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('core', '0001_initial'),
        ('passwordfolders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1024)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=1024)),
                ('url', models.CharField(max_length=1024, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='passwordfolders.PasswordFolder')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.Owner')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'db_table': 'enterpass_password',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PasswordACL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('api', models.BooleanField(default=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('password', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='passwords.Password')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enterpass_passwordacl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PasswordType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'enterpass_passwordtype',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='password',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='passwords.PasswordType'),
        ),
    ]
